/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Dimensions } from 'react-native';
import ThanBaseBridge, { TBGallery } from 'react-native-than-base-bridge';
const { width, height } = Dimensions.get('window');

export default class App extends Component<{}> {

  componentDidMount(){
   this.checkGalleryAuthorization();
  }

  checkGalleryAuthorization = async () => {
    ThanBaseBridge.checkGalleryAuthorization().then(result => {
      console.log({ result })
    }).catch((error) => {
      console.log({ error })
    })
  }

  render() {
   
    return (
      <TBGallery style={{ width, height }}/>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
